name: tag-release
on:
  schedule:
    - cron: "0 1 * * 1-5" # run at 1 AM UTC on weekdays
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag release if changes
    steps:
      - uses: findy-network/releaser-action@v5.1
        with:
          # use personal access token so that events are created for tag push
          token: ${{ secrets.RELEASER_PAT }}
          gate: test,iop
